ECommerce/urls.py
from django.contrib import admin
from django.urls import path,include


admin.site.site_header = "Molla Shop Adminstration"
admin.site.index_title="Admin"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("shop.urls")),

]

shop/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = "shop"
urlpatterns = [
    path('',views.index, name = "index"),
    path('login/',views.logIn, name = "login"),
    path('signup/',views.signup, name = "signup"),
    path('about/',views.about, name = "about"),
    path('contact/',views.contact, name = "contact"),
    path('cart/',views.cart, name = "cart"),
    path('account/<str:username>',views.account, name = "account"),
    path('checkout/',views.checkout, name = "checkout"),
    path('product/<int:product_id>',views.product, name = "product"),
    path('categories/<int:category_id>',views.categories, name = "categories"),
    path('addFromProduct/<int:productId>',views.addFromProduct, name = "addFromProduct"),
    path('setcart/',views.setcart, name = "setcart"),
    path('signout/',views.logOut, name = "signout"),
    path('order/',views.order, name = "order"),
    path('orders/',views.myOrders, name = "orders"),
    path('message/',views.message, name = "message"),
    

]

    
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Category(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.title
    class Meta:
        ordering = ['title']


class Product(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    unit_price = models.DecimalField(max_digits=6, decimal_places=2)
    inventory = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT,related_name="products")
    image = models.ImageField()

    def __str__(self) -> str:
        return self.title
    class Meta:
        ordering = ['title']


class Customer(AbstractUser):
    phone = models.CharField(max_length=255,null=True)
    country = models.CharField(max_length=255,null=True)
    postal_code = models.CharField(max_length=50,null=True)
    town = models.CharField(max_length=255,null=True)
    state = models.CharField(max_length=255,null=True)


    def __str__(self) -> str:
        return self.first_name + ' ' + self.last_name
    class Meta:
        ordering = ['first_name','last_name']




class Order(models.Model):

    PAYMENT_STATUS_PENDING = 'P'
    PAYMENT_STATUS_COMPLETE = 'C'
    PAYMENT_STATUS_FAILED = 'F'
    PAYMENT_STATUS_CHOICES = [
        (PAYMENT_STATUS_PENDING, 'Pending'),
        (PAYMENT_STATUS_COMPLETE, 'Complete'),
        (PAYMENT_STATUS_FAILED, 'Failed')
    ]
    payment_status = models.CharField(max_length=1, choices=PAYMENT_STATUS_CHOICES, default=PAYMENT_STATUS_PENDING)
    placed_at = models.DateTimeField(auto_now_add=True)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    complete = models.BooleanField(default=True)
    phone = models.CharField(max_length=20)
    country = models.CharField(max_length=255)
    postal_code = models.CharField(max_length=10)
    town = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    email = models.EmailField()
    total =models.BigIntegerField()
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)

 

    def __str__(self) -> str:
        return str(self.id)




class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.PROTECT)
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name = "ordered")
    quantity = models.PositiveSmallIntegerField()
    unit_price = models.DecimalField(max_digits=6, decimal_places=2)


    def __str__(self):
        return self.product.title




class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank=True,primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE,null=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE,null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.product.title
class Message(models.Model):
    first_name = models.CharField(max_length=255,editable=False)
    last_name = models.CharField(max_length=255,editable=False)
    email = models.EmailField(max_length=255,editable=False)
    phone = models.CharField(max_length=20,editable=False)
    subject = models.CharField(max_length=255, null=True,editable=False)
    message = models.TextField(editable=False)
    

shop/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.urls import reverse
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.db.models import Count
import requests
from .forms import *

import json
from .models import *



def index(request):
    if request.method == "GET":
        products = list(Product.objects.annotate(no_sold = Count('ordered')).order_by('-no_sold').filter(inventory__gt = 0))
        return render(request,"shop/index.html",{'products': products})
    else:
        val = request.POST.get("query")
        products = Product.objects.filter(Q(title__icontains = val) | Q(description__icontains = val))
        return render(request,"shop/index.html",{'products':products,'search':val})

def logIn(request):
    if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            # Authenticate the user
            user = authenticate(request, username=username, password=password)

            if user is not None:
                # Log in the user

                products = {}

                try:
                    cart = Cart.objects.get(cart_id = _cart_id(request))
                    cart_item = CartItem.objects.filter(cart = cart)
                    for item in cart_item:
                        products[item.product.title] = item.id

                except:
                    pass



                exisiting_products = {}
                cart_item = CartItem.objects.filter(customer__id = user.id)
                for item in cart_item:
                    exisiting_products[item.product.title] = item.id

                for product in products.keys():
                    if product in exisiting_products:
                        print(exisiting_products,product)
                        eitem = CartItem.objects.get(id = exisiting_products[product])
                        nitem = CartItem.objects.get(id = products[product])
                        eitem.quantity += nitem.quantity
                        if eitem.product.inventory < eitem.quantity:
                            eitem.quantity = eitem.product.inventory
                        # item.customer = Customer.objects.get(pk = user.id)
                        eitem.save()
                    else:
                        cart_item = CartItem.objects.get(id = products[product])
                        item.customer = Customer.objects.get(id = user.id)
                        item.save()




                login(request, user)

                url = request.META.get("HTTP_REFERER")
                try:
                    query = requests.utils.urlparse(url).query
                    params = dict([x.split('=') for x in query.split('&')])
                    if 'next' in params:
                        return redirect(params['next'])
                except:
                    return redirect('shop:account', username = user.username)

            # Authentication failed, show an error message
            else:
                message = "Username or password is Incorrect"
                return render(request, 'shop/login.html', {'message': message,'username':username,'password':password})

    return render(request, 'shop/login.html')

def signup(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            # confirmation email
            return redirect('shop:login')  # Redirect to the login page after successful signup
    else:
        form = SignUpForm()
        return render(request,"shop/signup.html",{'form':form})

    return render(request,"shop/signup.html",{'form':form})



def logOut(request):
    logout(request)
    return redirect('shop:index')

def contact(request):
    return render(request,"shop/contact.html")

def about(request):
    return render(request,"shop/about.html")

def _cart_id(request):
        cart = request.session.session_key
        if  cart == None:
            request.session.create()
            cart = request.session.session_key

        return cart

def cart(request):

    if request.method != "POST":
        country_vat = 0.15
        subtotal = 0

        try:
            if request.user.is_authenticated:
                cart_items = CartItem.objects.filter(customer__id = request.user.id)

            else:
                cart = Cart.objects.get(cart_id = _cart_id(request))
                cart_items = CartItem.objects.filter(cart = cart)

            for cart_item in cart_items:
                subtotal += (float(cart_item.product.unit_price) * cart_item.quantity)
        except ObjectDoesNotExist:
            cart_items = None


        total = subtotal + subtotal * country_vat
        return render(request,"shop/cart.html",{'cart_items':cart_items,'total':total,'subtotal':subtotal,'vat':country_vat*subtotal})

    else:
        data = json.loads(request.body)
        productId = data['productId']
        action = data['action']

        product = Product.objects.get(id = int(productId))
        try:
            cart = Cart.objects.get(cart_id = _cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id = _cart_id(request)
            )
        cart.save()

        if request.user.is_authenticated:
            if action == "add":
                try:
                    cart_item = CartItem.objects.get(product = product, customer__id = request.user.id)
                    cart_item.quantity += 1
                    cart_item.save()
                except CartItem.DoesNotExist:
                    cart_item = CartItem.objects.create(
                        product = product,
                        cart = cart,
                        quantity = 1,
                        customer = Customer.objects.get(id = request.user.id)
                    )
                    cart_item.save()

                if cart_item.quantity>product.inventory:
                    cart_item.quantity = product.inventory
                    cart_item.save()


            elif action == "remove":
                CartItem.objects.filter(product=product,customer__id = request.user.id).delete()
            return JsonResponse("Added To Cart",safe=False)




        else:
            if action == "add":
                try:
                    cart_item = CartItem.objects.get(product = product,cart=cart)
                    cart_item.quantity += 1
                    cart_item.save()
                except CartItem.DoesNotExist:
                    cart_item = CartItem.objects.create(
                        product = product,
                        cart = cart,
                        quantity = 1
                    )
                    cart_item.save()

                    if cart_item.quantity>product.inventory:
                        cart_item.quantity = product.inventory
                        cart_item.save()



            elif action == "remove":
                CartItem.objects.filter(product=product,cart=cart).delete()

            return JsonResponse("Added To Cart",safe=False)


def addFromProduct(request,productId):

    quantity = int(request.POST.get("quantity"))
    product = Product.objects.get(id = int(productId))

    try:
        cart = Cart.objects.get(cart_id = _cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
                cart_id = _cart_id(request)
                )
        cart.save()
    if request.user.is_authenticated:

            try:
                cart_item = CartItem.objects.get(product = product, customer__id = request.user.id)
                cart_item.quantity += quantity
                cart_item.save()
            except CartItem.DoesNotExist:
                cart_item = CartItem.objects.create(
                    product = product,
                    cart = cart,
                    quantity = quantity,
                    customer = Customer.objects.get(id = request.user.id)
                )
                cart_item.save()

            if cart_item.quantity>product.inventory:
                cart_item.quantity = product.inventory
                cart_item.save()


    else:

        try:
            cart_item = CartItem.objects.get(product = product,cart=cart)
            cart_item.quantity += quantity
            cart_item.save()
        except CartItem.DoesNotExist:
            cart_item = CartItem.objects.create(
                product = product,
                cart = cart,
                quantity = quantity
            )

            cart_item.save()

        if cart_item.quantity>product.inventory:
            cart_item.quantity = product.inventory
            cart_item.save()


    return redirect("shop:product",product_id = productId)


def setcart(request):


    data = json.loads(request.body)
    productId = data['productId']
    value = data['value']

    product = Product.objects.get(id = int(productId))

    try:
        cart = Cart.objects.get(cart_id = _cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = _cart_id(request)
        )
    cart.save()

    if request.user.is_authenticated:

        # try:
        cart_item = CartItem.objects.get(product = product,customer__id=request.user.id)
        cart_item.quantity = int(value)
        cart_item.save()
        if cart_item.quantity>product.inventory:
            cart_item.quantity = product.inventory
            cart_item.save()
        # except CartItem.DoesNotExist:
        #     cart_item = CartItem.objects.create(

shop/templates/shop/account.html
{% extends "shop/layout.html" %}
{% block body %}
       <main class="main">
        	<div class=" text-center" style="background-image: url('assets/images/page-header-bg.jpg')">
        		<div class="container">
        			<h1 class="page-title">Account</h1>
        		</div><!-- End .container -->
        	</div><!-- End .page-header -->
            <div class="page-content">
            	<div class="dashboard">
	                <div class="container">
	                	<div class="row">
	                		<aside class="col-md-4 col-lg-3">
	                			<ul class="nav nav-dashboard flex-column mb-3 mb-md-0" role="tablist">
								    <li class="nav-item">
								        <a class="nav-link active" id="tab-account-link" data-toggle="tab" href="#tab-account" role="tab" aria-controls="tab-account" aria-selected="true">Account Details</a>
								    </li>
									<li class="nav-item">
								        <a class="nav-link " id="tab-orders-link" data-toggle="tab" href="#tab-orders" role="tab" aria-controls="tab-orders" aria-selected="true">Orders</a>
									</li>
								    <li class="nav-item">
								        <a class="nav-link" href="{% url 'shop:signout' %}">Sign Out</a>
								    </li>
								</ul>
	                		</aside><!-- End .col-lg-3 -->
	                		<div class="col-md-8 col-lg-9">
	                			<div class="tab-content">
								    <div class="tab-pane fade" id="tab-orders" role="tabpanel" aria-labelledby="tab-orders-link">
										{% if not orders %}
											<p>No order has been made yet.</p>
											<a href="category.html" class="btn btn-outline-primary-2"><span>GO SHOP</span><i class="icon-long-arrow-right"></i></a>
										{% else %}
											<table class="table table-cart table-mobile">
												<thead>
													<tr>
														<th>Order Id</th>
														<th>Billing Name</th>
														<th>Order Total</th>
														<th>Date</th>
													</tr>
												</thead>
												<tbody>
													{% for order in orders %}
														<tr>
															<td>{{order.id}}</td>
															<td>{{order.first_name}} {{order.last_name}}</td>
															<td>{{order.total}}</td>
															<td>{{order.placed_at}}</td>
														</tr>
													{% endfor%}
												</tbody>

											</table>
										{%endif%}
										
								    </div><!-- .End .tab-pane -->
								    <div class="tab-pane fade show active" id="tab-account" role="tabpanel" aria-labelledby="tab-account-link">
								    	<form action="{% url 'shop:account' request.user.username %}" method = 'post'>
											{% csrf_token %}
			                				<div class="row">
			                					<div class="col-sm-6">
			                						<label>First Name </label>
													{{form.first_name}}
			                						{% comment %} <input type="text" name = "firstName" value = "{{customer.first_name}}" class="form-control" value =  "" required> {% endcomment %}
			                					</div><!-- End .col-sm-6 -->

			                					<div class="col-sm-6">
			                						<label>Last Name *</label>
													{{form.last_name}}
			                						{% comment %} <input type="text" name = "lastName"class="form-control" value = "{{customer.last_name}}" required> {% endcomment %}
			                					</div><!-- End .col-sm-6 -->
			                				</div><!-- End .row -->

											<div class = row>

												<div class = col-sm-6>
													<label>Username *</label>
													{{form.username}}
													{% if form.username.errors %}
														<div class="error" style = "color:red;">{{ form.username.errors }}</div>
													{% endif %}
													{% comment %} <input type="text" name = "userName" class="form-control"value = "{{customer.username}}" required> {% endcomment %}
												</div>

												<div class = col-sm-6>
													<label>Email address *</label>
													{{form.email}}
													{% if form.email.errors %}
														<div class="error" style = "color:red;">{{ form.email.errors }}</div>
													{% endif %}
													{% comment %} <input type="email" name = "email"class="form-control" value = "{{customer.email}}" required> {% endcomment %}
												</div>
											</div>

											<div class = row>

												<div class = col-sm-6>
													<label>Phone No </label>
													<input type="phone" name = "phone"{% if customer.phone %} value = "{{customer.phone}}" {% else %} placeholder = "Phone" {%endif%} class="form-control" >
												</div>

												<div class = col-sm-6>	
													<label>Postal Code </label>
													<input type="text" name = "postal_code"class="form-control" {% if customer.postal_code %} value = "{{customer.postal_code}}" {% else %} placeholder = "Postal code" {%endif%}> 
												</div>
											</div>


											<div class = row>
												<div class = col-sm-4>
													<label>Country </label>
													<input type="text" name = "country" class="form-control" {% if customer.country %} value = "{{customer.country}}" {% else %} placeholder = "Country" {%endif%}>
												</div>

												<div class = col-sm-4>
													<label>State </label>
													<input type="text" name = "state" class="form-control" {% if customer.state %} value = "{{customer.state}}" {% else %} placeholder = "State" {%endif%}>
												</div>


												<div class = col-sm-4>
													<label>Town/City </label>
													<input type="text" name = "town" class="form-control" {% if customer.town %} value = "{{customer.town}}" {% else %} placeholder = "Town" {%endif%}>
												</div>
											</div>


		            						<label>Current password (leave blank to leave unchanged)</label>
		            						<input type="password" name = "current_password" class="form-control">
											<div class="error" style = "color:red;">{{ passmessage }}</div>


		            						<label>New password (leave blank to leave unchanged)</label>
		            						<input type="password" name = "new_password" class="form-control">

		            						<label>Confirm new password</label>
		            						<input type="password" name = "confirm_password"class="form-control mb-2">
											<div class="error" style = "color:red;">{{ confmessage }}</div>


		                					<button type="submit" class="btn btn-outline-primary-2">
			                					<span>SAVE CHANGES</span>
			            						<i class="icon-long-arrow-right"></i>
			                				</button>
											
			                			</form>
								    </div><!-- .End .tab-pane -->
								</div>
	                		</div><!-- End .col-lg-9 -->
	                	</div><!-- End .row -->
	                </div><!-- End .container -->
                </div><!-- End .dashboard -->
            </div><!-- End .page-content -->
        </main><!-- End .main -->
{% endblock body %}
        

shop/templates/shop/index.html
{% extends "shop/layout.html" %}
{%load static%}
{% block body %}
    <div class="container top">
        <div class="heading heading-flex mb-3">
            <div class="heading-left">
                <h2 class="title" style="margin-top: 20px;">{% if search %} Search result for {{search}}: {%else%} Top Selling Products{%endif%}</h2><!-- End .title -->
            </div><!-- End .heading-left -->


        </div><!-- End .heading -->

        <div class="tab-content tab-content-carousel just-action-icons-sm">
            <div class="tab-pane p-0 fade show active" id="top-all-tab" role="tabpanel"
                aria-labelledby="top-all-link">
                <div class="owl-carousel owl-full carousel-equal-height carousel-with-shadow" data-toggle="owl"
                    data-owl-options='{
                        "nav": true, 
                        "dots": false,
                        "margin": 20,
                        "loop": false,
                        "responsive": {
                            "0": {
                                "items":2
                            },
                            "480": {
                                "items":2
                            },
                            "768": {
                                "items":3
                            },
                            "992": {
                                "items":4
                            },
                            "1200": {
                                "items":5
                            }
                        }
                    }'>

                    {% for product in products%}
                        <div class="product product-2">
                            <figure class="product-media">
                                <a href="{% url 'shop:product' product.id %}">
                                    <img src="{{product.image.url}}"
                                        alt="Product image" class="product-image">
                                </a>

                                <div class="product-action action-icon-top">
                                    <a href="" data-product = {{product.id}} data-action = "add" class="  btn-product btn-cart btn-product update-cart" title="Add to cart"><span>add to
                                        cart</span></a>
                                </div><!-- End .product-action -->
                            </figure><!-- End .product-media -->

                            <div class="product-body">
                                <div class="product-cat">
                                    <a href="{% url 'shop:categories' product.category.id %}">{{product.category}}</a>
                                </div><!-- End .product-cat -->
                                <h3 class="product-title"><a href="{% url 'shop:product' product.id %}">{{product.title}}</a>
                                </h3><!-- End .product-title -->
                                <div class="product-price">
                                    {{product.unit_price}}
                                </div><!-- End .product-price -->
                            </div><!-- End .product-body -->
                        </div><!-- End .product -->
                    
                    {% empty %}
                        <h3>There are No products at the moment.</h3>
                    {% endfor %}

                    
                </div><!-- End .owl-carousel -->
            </div><!-- .End .tab-pane -->
        </div><!-- End .tab-content -->
    </div><!-- End .container -->

    <div class="container">
        <hr class="mt-5 mb-0">
    </div><!-- End .container -->
    
{% endblock %}

shop/templates/shop/signup.html
{% extends "shop/layout.html" %}
{%block body %}
<div class="login-page bg-image pt-8 pb-8 pt-md-12 pb-md-12 pt-lg-17 pb-lg-17" style="background-image: url('static/login/images/backgrounds/login-bg.jpg')">
    <div class="container">
        <div class="form-box">
            <div class="form-tab">
                <ul class="nav nav-pills nav-fill" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="register-tab-2" href="{%url 'shop:signup' %}"  aria-controls="register-2" aria-selected="true">Register</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="register-2" role="tabpanel" aria-labelledby="register-tab-2">
                        <form method="post" action="{% url 'shop:signup' %}">
                            {% csrf_token %}

                            <div class="form-group">
                              <label for="id_first_name">First Name</label>
                              {{ form.first_name }}
                              {% if form.first_name.errors %}
                                <div class="error" style = "color:red;">{{ form.first_name.errors }}</div>
                              {% endif %}
                            </div>

                            <div class="form-group">
                              <label for="id_last_name">Last Name</label>
                              {{ form.last_name }}
                              {% if form.last_name.errors %}
                                <div class="error" style = "color:red;">{{ form.last_name.errors }}</div>
                              {% endif %}
                            </div>

                            <div class="form-group">
                              <label for="id_username">Username</label>
                              {{ form.username }}
                              {% if form.username.errors %}
                                <div class="error" style = "color:red;">{{ form.username.errors }}</div>
                              {% endif %}
                            </div>

                            <div class="form-group">
                              <label for="id_email">Your email address</label>
                              {{ form.email }}
                              {% if form.email.errors %}
                                <div class="error" style = "color:red;">{{ form.email.errors }}</div>
                              {% endif %}
                            </div>

                            <div class="form-group">
                              <label for="id_password">Password</label>
                              {{ form.password }}
                              {% if form.password.errors %}
                                <div class="error" style = "color:red;">{{ form.password.errors }}</div>
                              {% endif %}
                            </div>
                            <div class="form-group">
                                <label for="id_password">Confirm Password</label>
                                {{ form.confirm_password }}
                                {% if form.confirm_password.errors %}
                                  <div class="error" style = "color:red;">{{ form.confirm_password.errors }}</div>
                                {% endif %}
                              </div>
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="register-policy-2" required>
                                <label class="custom-control-label" for="register-policy-2">I agree to the <a href="#">privacy policy</a> *</label>
                            </div><!-- End .custom-checkbox -->

                            <button type="submit" class="btn btn-outline-primary-2">
                              <span>SIGN UP</span>
                              <i class="icon-long-arrow-right"></i>
                            </button>
                            <span style = "margin-left:10px;">Already Have an Account?</span>  <a href = "{%url 'shop:login'%}"><span style = "margin-left:10px;"><u>Sign In</u></span> </a>

                          </form>
                    </div><!-- .End .tab-pane -->
                </div><!-- End .tab-content -->
            </div><!-- End .form-tab -->
        </div><!-- End .form-box -->
    </div><!-- End .container -->
</div><!-- End .login-page section-bg -->
</main><!-- End .main -->
{%endblock%}